### ISSUE TITLE
Able to jump off Landing Map, but re-spawn puts me in an area where I cannot get back

### ISSUE THREAD

**Issue by ChrisD2012** [jasonsurratt/knockback-tickets#20]
**Describe the bug**
I can jump off the map, sorry I was wandering around and jumping to see if I can find a way to climb to the top peak (Did that I feel like that is an achievement). However when falling off the map, it does not re-spawn me back inside the map, but on the outside making it almost impossible to get back.

I found a way via the Skyrim jump method (Jump left, move, then jump right move) to get back to the top but, if you fall off you just keep getting spawned outside the map.

**To Reproduce**
1. Go to the graveyard and then head away from the house
2. you will come across an opening that you can jump into and then jump into that 
3. Keep going until you drop off the map and then you will respawn outside the map and not easily able to jump back into the map.

**Expected behavior**
Re-spawn back into the main map.
**Screenshots**
![image](https://user-images.githubusercontent.com/61132931/83222976-161b4c00-a1bd-11ea-838a-a3635df9e121.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Reporter**
Me

**Comment by jasonsurratt** [comment]
Thanks, @ChrisD2012! I know exactly what is going on. Whadaya think? Spawn back at the normal spawn location? Death?

**Comment by jasonsurratt** [comment]
I've changed it to respawn you at a network spawn point. We can always re-open and use death but given that there may be unexpected spots on every map where a player can squeeze through, it is a little more forgiving to respawn them immediately.

https://github.com/jasonsurratt/knockback/commit/76ea4dad1828db2bedd80e93a2b0ac9b0ae9ef89
https://github.com/jasonsurratt/knockback/commit/1512c6016e820d5fe39ba6e3703a366526329a05
