### ISSUE TITLE
Text on Menu Un-readable due to transparency 

### ISSUE THREAD

**Issue by ChrisD2012** [jasonsurratt/knockback-tickets#21]
**Describe the bug**
Play the game and open the menu, when looking at trees or something darker

**To Reproduce**
1. Go to look at something like tree's or dark background
2. Click on esc to open menu and go to input
3. Letters are unable to be seen

**Expected behavior**
White text may fix this due to the game's darker areas or remove transparency from menus.

**Screenshots**

<img width="961" alt="hard to read text in menu" src="https://user-images.githubusercontent.com/61132931/83223273-ce48f480-a1bd-11ea-8bd8-d61de48abdf5.PNG">
Report ME:) Dryliec

**Comment by jasonsurratt** [comment]
Good catch and easy fix. Thanks!

**Comment by jasonsurratt** [comment]
Fixed
https://github.com/jasonsurratt/knockback/commit/4f4ad7c03897379983b36351e161bdb031b20807
