### ISSUE TITLE
Double In Game Menu

### ISSUE THREAD

**Issue by ChrisD2012** [jasonsurratt/knockback-tickets#22]
**Describe the bug**
When jumping off the map I managed to press ESC and the menu you came up, upon re-spawning, I pressed it again and the menu appeared with double option see screengrab

**To Reproduce**
Only managed to do it twice, tested like 100 times.
1. Jump off the map, press ESC
2. Press ESC before you die
3. Exit and go back to game, re-spawn 
4. Press ESC again

**Expected behavior**
One menu to appear without overlaying over each other.

**Screenshots**

<img width="961" alt="Capture" src="https://user-images.githubusercontent.com/61132931/83224935-f6d2ed80-a1c1-11ea-8236-035b73ad450e.PNG">

**Reporter**
Me again ;)

**Comment by jasonsurratt** [comment]
Wowzers! Your persistence is commendable. Hmm. I'll see what I can do. Thanks!

**Comment by jasonsurratt** [comment]
Whoops.

**Comment by jasonsurratt** [comment]
So I couldn't recreate this one. However, I did modify the menu code to be more defensive. When the menu is enabled or a menu is changed the code ensures that only one menu panel is visible at a time. Hopefully, this resolves the problem.

https://github.com/jasonsurratt/knockback/commit/363b7434fc23097dc4fe1b90d7f94bc41301e70c
