### ISSUE TITLE
The starting area swinging barrel deals too much damage

### ISSUE THREAD

**Issue by ChrisD2012** [jasonsurratt/knockback-tickets#26]
**Describe the bug**
Jump at the floating barrow twice (Wizard) in the landing map and you die. it then takes you outside the map to await re-spawn

**To Reproduce**
1. Go to landing map
2. Jump at the floating barrow
3. Take Huge Damage
4. Die and it puts you out the map to await re-spawn, however you do re-spawn inside the map so win

**Expected behavior**

**Screenshots**
![20200601081927_1](https://user-images.githubusercontent.com/61132931/83363981-0a0fd400-a3e1-11ea-817d-b58a7440bfde.jpg)
![20200601081919_1](https://user-images.githubusercontent.com/61132931/83363985-1005b500-a3e1-11ea-884e-c20190c682cd.jpg)

**Reporter**
It's me again

**Comment by jasonsurratt** [comment]
Truth.

**Comment by jasonsurratt** [comment]
I reduced the damage to 20.
https://github.com/jasonsurratt/knockback/commit/91b06d9b252c94d219b7a1a09e2991f7776365ba
