### ISSUE TITLE
Can reach out of bounds in forest level

### ISSUE THREAD

**Issue by pridgey** [jasonsurratt/knockback-tickets#36]
**Describe the bug**
You can reach the edge of the map and jump off in the forest level

**To Reproduce**
1. Follow the path up the hill
2. Move through the tree branches
3. Viola

**Expected behavior**
There should likely be a wall preventing access beyond the map

**Screenshots**
https://drive.google.com/file/d/1AqHCFe-v5N0aQ4WNXVBd6Vop9M_IsDAl/view?usp=sharing

**Desktop (please complete the following information):**
- Windows 10

**Comment by jasonsurratt** [comment]
Hi Taylor! You're right, it should have a boundary. I just put that level there to get some feedback on the style and straight-up stole a demo scene as a placeholder. I have been playing with recreating an expansive environment using those assets and [MapMagic 2](https://assetstore.unity.com/packages/tools/terrain/mapmagic-2-165180) but it isn't ready yet.

**Comment by pridgey** [comment]
Sounds awesome! I liked the feel of the level for sure
